### ISSUE TITLE
Ettus E310 GIT_HASH error

### ISSUE THREAD

**Issue by rmd91** [EttusResearch/fpga#6]
I'm getting an error on GIT_BASH being undefined when I build the E310 design.

I ran this on a RedHat system with Vivado 2015.4.
$ source ./setupenv.sh --vivado-path=/mtcnas/tools/xilinx/2015.4/Vivado
$ make E310

ERROR: [Synth 8-2841] use of undefined macro GIT_HASH

I see where the Git hash is read (Makefile.e300.inc:79 SHORT_HASH=$(addprefix GIT_HASH=,$(shell ../../tools/scripts/git-hash.sh)), but I don't see where this gets passed to Vivado. As far as I can tell, the Git repo is in a working state. The hash I read from the command line is:

$ git rev-parse --verify HEAD --short
f592fc3

Running git status shows the branch is up-to-date.

EDIT: At the beginning of make E310, I see this:

BUILDER: Checking tools...
* GNU bash, version 4.2.51(2)-release (x86_64-unknown-linux-gnu)
* Python 2.7.5
* Vivado v2015.4 (64-bit)
../../tools/scripts/git-hash.sh: line 14: ${short_hash^^}: bad substitution

**Comment by mbr0wn** [comment]
@rmd91 We were not able to reproduce this. Also, we've been shipping with this feature for quite a while. I wonder if it's maybe your local setup? This line in particular confuses me:
```
 ../../tools/scripts/git-hash.sh: line 14: ${short_hash^^}: bad substitution
```

...because this is a simple git command and shouldn't fail. What's your distro version?
